### ISSUE TITLE
ServicePartitionResolver not returning stale value after a service reset

### ISSUE THREAD

**Issue by PeterStephenson** [mikegore1000/ServiceFabricGateway#1] opened 2017-05-30 09:26 UTC
# Steps to reproduce
1. Launch ServiceFabricGateway
1. Launch a test service and connect to it successfully through the gateway
1. Stop and start the test service (do not use a rolling upgrade for this)
1. Hit the test service again

# Expected behaviour
The second request through ServiceFabricGateway should use the new port that was randomly assigned when the service was restarted (note: rolling upgrades appear to preserve the port).

# Actual behaviour
The second request through ServiceFabricGateway uses the port from the original request through ServiceFabricGateway which is the one assigned during the initial launch of the test service. 

# Mitigation
Restarting the ServiceFabricGateway application appears to cause ServiceFabricGateway to locate the new port.
This indicates that the caching is probably client side and some kind of cache invalidation strategy may be needed.

**Comment by PeterStephenson** [comment] 2017-05-30 09:26
@mikegore1000 I couldn't raise this on the ASOS fork, so I've raised it here. Hopefully that's ok?

**Comment by mikegore1000** [comment] 2017-06-01 07:10
The code has now been updated.  Tests on a local cluster seemed to confirm the issue is resolved.  Let me know if it's fixed everything on your side and I'll close the issue down.

**Comment by mikegore1000** [comment] 2017-06-01 10:46
Closing as we've proven the issue has been corrected.

**Closed as completed by mikegore1000** 2017-06-01 10:46 UTC
Labels: bug
